apiVersion: v1
kind: Service
metadata:
  name: app1-service-np
  labels:
    name: app1-deploy
    app: app1-app
spec:
  type: NodePort
  selector:
    app: app1-app
  ports:
    - protocol: TCP
      port: 3500
      nodePort: 30027



    