apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deploy
  labels:
    name: app2-deploy
    app: app2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app2-pod
      app: app2-app
  template:
    metadata:
      name: app2-pod
      labels:
        name: app2-pod
        app: app2-app
    spec:
      containers:
        - name: app2-container
          image: "590677500889.dkr.ecr.us-east-1.amazonaws.com/app2-repository:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: /estoyvivo
              port: 4500
            initialDelaySeconds: 5
            periodSeconds: 5