apiVersion: v1
kind: Service
metadata:
  name: app2-service-np
  labels:
    name: app2-deploy
    app: app2-app
spec:
  type: NodePort
  selector:
    app: app2-app
  ports:
    - protocol: TCP
      port: 4500
      nodePort: 30127



    